### ISSUE TITLE
Messed Up Sliders On Game Preferences

### ISSUE THREAD

**Issue by turd-ferguson** [falltergeist/falltergeist#421]
At 1024x768 resolution some of the sliders are messed up on the preferences panel.

This leads me to believe the sliders are not placed relative to the preferences panel, but to the game screen, which won't work at different resolutions.

![sliders](http://i.imgur.com/NCg3U3P.png)

**Comment by phobos2077** [comment]
The reason for this bug is in State::addUI method. It changes UI position by following code:
```
    // Add to UI state position
    ui->setPosition(ui->position() + position());
```
However, ui->position() returns base position + offset (by design) and ui->setPosition() only changes the base position. If UI offset is not 0 at the moment of addUI call, base position becomes messed up.
Need to consider re-designing how position/setPosition works. May be related to #415.
