### ISSUE TITLE
Lot of opcode handlers (duplications)

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [falltergeist/falltergeist#503]
I know that you guys are staying against the usage of macros but it looks way more better when using them for code generation:

https://github.com/Sh1ft0x0EF/falltergeist/blob/dev/src/VM/Handler/OpcodeHandlers.h
https://github.com/Sh1ft0x0EF/falltergeist/blob/dev/src/VM/Handler/OpcodeHandlers.cpp

**Comment by phobos2077** [comment]
What is this code? We have all opcode handlers in separate files like ages ago :)
If you want to show good example of macro usage, use the actual code structure as a basis.

I personally not against macro when used for good purpose and there is no non-macro solution. But project founder was very clearly against any kind of macro in our code. So I really not sure what can be done about this. I had some ideas for refactoring opcode handlers (reduce amount of boilerplate and huge number of unnecessary files), but this is not in priority right now.

**Comment by Sh1ft0x0EF** [comment]
You mean something like (similar to event system):
* a union that contains every handled opcode data;
* switch block that contains handling for the opcodes?

**Comment by phobos2077** [comment]
No I mean something like this:
All opcodes in one table:
https://github.com/phobos2077/sfall/blob/develop/sfall/Modules/Scripting/Opcodes.cpp#L65
(one line per opcode, easy to read and modify)

Example opcode handler:
https://github.com/phobos2077/sfall/blob/develop/sfall/Modules/Scripting/Handlers/Objects.cpp#L360
(just one function)

Basically this solution revolves around function pointers. All handlers are just static non-member functions, and you can easily store pointers to such functions in structs. The state is passed as the first argument.

I'm not sure if it possible to do something similar but using classes instead of functions. Maybe some template magic can help.

**Comment by Sh1ft0x0EF** [comment]
Metamod works similar to this approach:
https://github.com/Sh1ft0x0EF/metamod-xash/blob/master/metamod/api_info.cpp#L43

Using classes... Create some base class that have a virtual method called somehow like HandleOpcode or something that does nothing by default and receives a ref to OpcodeContext or something more general. Something that could provide info about the opcode type to be able to use switch block and handle some common in functionality ops

**Comment by Sh1ft0x0EF** [comment]
UPD:
So what I means is to allow the new system on classes to handle more than one opcode by a single handler class

**Comment by alexeevdv** [comment]
It is already done for comparison opcode handler for example

**Comment by phobos2077** [comment]
Refactoring handlers may prove useful, but right now it's low priority. I would try to do it after 0.4 release :)

**Comment by Sh1ft0x0EF** [comment]
Understood
